export interface McpToolCatalogEntry {
  name: string;
  category: string;
  description: string;
}

export const LMBRAIN_MCP_TOOLS: McpToolCatalogEntry[] = [
  { name: "spec_ready", category: "Spec", description: "Approve a backlog spec to ready (on operator request)." },
  { name: "spec_start", category: "Spec", description: "Implementation specialist only: move an assigned ready spec to working." },
  { name: "spec_submit", category: "Spec", description: "Implementation specialist only: submit a completed working spec for review." },
  { name: "spec_done", category: "Spec", description: "Project Lead closeout after accepted review, checked criteria, and evidence." },
  { name: "spec_discard", category: "Spec", description: "Discard a spec (requires operator approval)." },
  { name: "spec_park", category: "Spec", description: "Project Lead: park a ready spec in backlog with preserved reason and history." },
  { name: "spec_dependencies_set", category: "Spec", description: "Replace backlog hard prerequisites with graph validation, audit, and stale-write protection." },
  { name: "spec_set_verification_gates", category: "Spec", description: "Replace the executable gate contract a spec declares, validated against the current verification manifest, with audit history and stale-write protection." },
  { name: "spec_dependency_context", category: "Context", description: "Inspect direct, dependent, transitive, and blocking hard-spec relationships. Read-only." },
  { name: "spec_dependency_candidates", category: "Context", description: "Inventory explicit legacy hard-dependency prose without promoting it. Read-only." },
  { name: "review_accept", category: "Review", description: "Accept a review and record the verdict event on explicit operator request." },
  { name: "review_changes_requested", category: "Review", description: "Request changes with a required rationale and evidence references." },
  { name: "review_block", category: "Review", description: "Block a review with a required rationale and evidence references." },
  { name: "review_supersede", category: "Review", description: "Supersede a review while preserving its verdict history." },
  { name: "review_remediation", category: "Review", description: "Record an attributable remediation attempt without changing review status." },
  { name: "review_escalate", category: "Review", description: "Record an operator-authorized escalation without changing review status." },
  { name: "review_takeover", category: "Review", description: "Record an operator-authorized bounded corrective takeover." },
  { name: "review_set_implementation_agent", category: "Review", description: "Project Lead: correct a provably wrong implementation_agent attribution; appends an attribution-correction event, never edits history." },
  { name: "spec_attest_operator_delegated", category: "Verification", description: "Project Lead: record an operator attestation granted out of band (named operator, channel, quoted authorization); satisfies the gate without force, auditable as delegated." },
  { name: "review_remediation_verified", category: "Review", description: "Project Lead: record verification of a remediation cycle without changing review status." },
  { name: "review_migration_preview", category: "Review", description: "Preview lifecycle and taxonomy migration coverage without rewriting reviews." },
  { name: "debt_create", category: "Debt", description: "Create a governed debt with taxonomy category, severity, and evidence." },
  { name: "debt_context", category: "Debt", description: "Debt context pack: linked artifacts, lifecycle events, diagnostics. Read-only." },
  { name: "debt_candidates", category: "Debt", description: "Inventory review debts eligible for promotion. Read-only." },
  { name: "debt_plan", category: "Debt", description: "Link a debt to the spec that will resolve it." },
  { name: "debt_resolve", category: "Debt", description: "Resolve a debt with evidence references." },
  { name: "debt_defer", category: "Debt", description: "Defer a debt with a reason and revisit condition." },
  { name: "debt_accept_risk", category: "Debt", description: "Accept a debt's risk with an audited rationale (on operator request)." },
  { name: "debt_reopen", category: "Debt", description: "Reopen a resolved, deferred, or risk-accepted debt." },
  { name: "debt_supersede", category: "Debt", description: "Supersede a debt with a newer one, writing both sides." },
  { name: "debt_migration_preview", category: "Debt", description: "Preview the versioned legacy durable-ID migration without writing." },
  { name: "debt_migrate", category: "Debt", description: "Apply an operator-confirmed migration bound to the exact preview digest." },
  { name: "kit_migration_preview", category: "Kit", description: "Preview and classify kit-owned vs project-owned files for kit upgrade." },
  { name: "kit_migrate", category: "Kit", description: "Apply operator-confirmed atomic kit upgrade to the target version." },
  { name: "wayfinder_overview", category: "Wayfinder", description: "Read-only experimental decision-map summaries. Wayfinder is opt-in shaping, never an implementation board." },
  { name: "wayfinder_map_context", category: "Wayfinder", description: "Read-only bounded map context: destination, fog, frontier, claimed/blocked tickets, resolved decisions and diagnostics." },
  { name: "wayfinder_map_create", category: "Wayfinder", description: "Project Lead: create an opt-in decision map only after the operator agrees that a multi-session uncertain route needs charting. Does not authorize implementation." },
  { name: "wayfinder_ticket_create", category: "Wayfinder", description: "Project Lead: create one bounded decision, research, prototype, or prerequisite ticket. A ticket is not production implementation work." },
  { name: "wayfinder_ticket_claim", category: "Wayfinder", description: "Project Lead: claim one frontier ticket to avoid concurrent duplicate decision work." },
  { name: "wayfinder_ticket_resolve", category: "Wayfinder", description: "Project Lead: resolve a bounded ticket with evidence. Conversation/prototype tickets additionally require explicit operator evidence." },
  { name: "wayfinder_map_clear", category: "Wayfinder", description: "Project Lead: clear a map only when all fog and tickets are resolved and diagnostics are empty. Clearing recommends normal SPEC creation; it never starts implementation." },
  { name: "dream_capture", category: "Dream", description: "Project Lead: capture a grounded, tentative technical- or design-debt observation after an explicit operator invitation to dream." },
  { name: "spec_set_effort", category: "Spec", description: "Project Lead: set the implementation estimate (capability tier and thinking level)." },
  { name: "spec_set_tags", category: "Spec", description: "Project Lead: replace a spec's tags after taxonomy validation." },
  { name: "spec_record_effort_observation", category: "Spec", description: "Specialist: record the effort the work actually required as evidence; never rewrites the estimate." },
  { name: "spec_attest_lead", category: "Spec", description: "Project Lead: record a typed attestation for an owner=lead verification gate." },
  { name: "adr_accept", category: "ADR", description: "Accept a proposed ADR (on operator request)." },
  { name: "adr_reject", category: "ADR", description: "Reject a proposed ADR (on operator request)." },
  { name: "adr_supersede", category: "ADR", description: "Project Lead: retire a decision in favour of an accepted one, writing both sides. Idempotent." },
  { name: "agent_activate", category: "Agent", description: "Activate a proposed agent profile (on operator request)." },
  { name: "agent_deactivate", category: "Agent", description: "Deactivate an agent profile (on operator request)." },
  { name: "agent_proposal_approve", category: "Agent", description: "Approve a governed agent proposal on explicit operator request." },
  { name: "agent_proposal_reject", category: "Agent", description: "Reject a governed agent proposal on explicit operator request." },
  { name: "agent_improvement_signals", category: "Learning", description: "Aggregate repeated review categories and per-profile effectiveness metrics. Read-only." },
  { name: "agent_improvement_propose", category: "Learning", description: "Create an evidence-linked additive profile improvement proposal." },
  { name: "agent_improvement_apply", category: "Learning", description: "Apply an approved, non-stale improvement proposal atomically." },
  { name: "skill_activate", category: "Skill", description: "Activate a proposed project-scoped skill (on operator request)." },
  { name: "skill_retire", category: "Skill", description: "Retire a project-scoped skill that should no longer be recommended." },
  { name: "handoff_consume", category: "Handoff", description: "Consume a ready session handoff (Project Lead only, after validation)." },
  { name: "handoff_supersede", category: "Handoff", description: "Supersede a ready session handoff with a newer one." },
  { name: "handoff_archive", category: "Handoff", description: "Archive/retire a session handoff." },
  { name: "lmbrain_create", category: "Create", description: "Create an artifact with an allocated ID." },
  { name: "lmbrain_set_recommended_agent", category: "Setter", description: "Set a spec's recommended agent." },
  { name: "lmbrain_set_agent_mnemonic_name", category: "Setter", description: "Set an agent profile's mnemonic human name." },
  { name: "lmbrain_get_artifact", category: "Read", description: "Read a repository artifact." },
  { name: "lmbrain_validate", category: "Read", description: "Validate controlled-mutation invariants." },
  { name: "lmbrain_repair_frontmatter", category: "Repair", description: "Operator-authorized: merge duplicate top-level frontmatter keys left by failed mutations; audited, refuses ambiguity." },
  { name: "branching_strategy_get", category: "Branching", description: "Read the declared project branching strategy and summary digest. Read-only." },
  { name: "branching_strategy_set", category: "Branching", description: "Project Lead: declare the project branching strategy with actor and reason (on operator request)." },
  { name: "harness_config_get", category: "Environment", description: "Read and validate project harness intent. Read-only." },
  { name: "harness_config_validate", category: "Environment", description: "Validate a complete candidate harness manifest without writing it." },
  { name: "harness_config_set", category: "Environment", description: "Atomically replace the project harness manifest after strict validation; approval and apply remain separate Lead actions." },
  { name: "harness_approval_status", category: "Environment", description: "Read the machine-local harness approval state. Read-only." },
  { name: "harness_plan_preview", category: "Environment", description: "Deterministic preview of native host files, readiness, and conflicts. Read-only." },
  { name: "harness_manifest_approve", category: "Environment", description: "Project Lead: approve the exact previewed manifest digest for this workspace; audited." },
  { name: "harness_approval_revoke", category: "Environment", description: "Project Lead: revoke this workspace's harness approval; audited." },
  { name: "harness_config_apply", category: "Environment", description: "Project Lead: materialize the approved manifest into native host files atomically with rollback and drift hashes; audited." },
  { name: "harness_drift_status", category: "Environment", description: "Compare applied native-file hashes against disk and report drift. Read-only." },
  { name: "lmbrain_feedback_record", category: "Feedback", description: "Project Lead: append an evidence-backed observation about LMBrain itself without changing project state." },
  { name: "lmbrain_feedback_report", category: "Feedback", description: "Read the portable typed LMBrain kit-feedback report with derived per-note status. Read-only." },
  { name: "lmbrain_feedback_resolve", category: "Feedback", description: "Project Lead: append a resolved/reconfirmed lifecycle event to a kit-feedback note; the note itself is never edited." },
  { name: "lmbrain_list_ready_handoffs", category: "Read", description: "List ready handoffs." },
  { name: "lmbrain_project_digest", category: "Context", description: "Bounded project orientation with declared/derived state, all spec lifecycle counts, roadmap reconciliation, actionable diagnostics, and exact omitted counts. Read-only." },
  { name: "lmbrain_spec_context", category: "Context", description: "Spec handoff context: metadata, acceptance criteria, linked decisions, agent profile, files, diagnostics. Read-only." },
  { name: "lmbrain_review_context", category: "Context", description: "Review context: acceptance criteria, implementation evidence, linked reviews, decisions, verification commands. Read-only." },
  { name: "verification_manifest_get", category: "Verification", description: "Inspect and validate the repository verification manifest. Read-only." },
  { name: "verification_manifest_status", category: "Verification", description: "Report manifest state (absent, unapproved, approved, stale, …) with a next action. Read-only." },
  { name: "verification_manifest_init", category: "Verification", description: "Bounded deterministic gate discovery preview from repository metadata; never executes commands." },
  { name: "verification_manifest_validate", category: "Verification", description: "Validate complete manifest TOML without writing it." },
  { name: "verification_manifest_set", category: "Verification", description: "Atomically replace the manifest with stale-write protection; keeps one recoverable previous version." },
  { name: "verification_manifest_rollback", category: "Verification", description: "Restore the recoverable previous manifest with the same stale-write protection." },
  { name: "verification_manifest_approve", category: "Verification", description: "Project Lead: approve the exact manifest digest for this workspace." },
  { name: "verification_migration_preview", category: "Verification", description: "Conservative preview for legacy operator-owned before-done gates; never rewrites specs. Read-only." },
  { name: "spec_verify", category: "Verification", description: "Execute approved named gates and write an attributable bounded transcript." },
];
