use std::path::PathBuf;
use ts_rs::TS;

use lmbrain_core::{
    transitions::{
        AdrStatus, AgentProposalStatus, AgentStatus, DebtStatus, HandoffStatus, McpProposalStatus,
        McpStatus, ReviewStatus, SkillStatus, SpecStatus,
    },
    BranchAuthorityConfig, BranchNamingConfig, BranchingStrategy, BranchingTopology,
    CommitTriggersConfig, Debt, DebtCandidate, DebtCandidateInventory, DebtContext, Diagnostic,
    DiagnosticFixability, DiagnosticSeverity, Dream, KitFeedbackNote, KitFeedbackNoteStatus,
    KitFeedbackReport, KitFeedbackResolution, OperatorGate, RelationSummary, ReviewEventHistory,
    ReviewEventInput, ReviewHistorySource, ReviewLifecycleAnalysis, ReviewLifecycleEvent,
    Roadmap, RoadmapMilestone, VerificationAttestation, VerificationGate, VerificationManifest,
};

use lmbrain_lib::models::{
    adr::Adr,
    agent::{AgentProfile, AgentProposal},
    design::{DesignMockup, DesignMockupHtml, DesignMockupKind},
    file::{DirEntry, FileContent, FileEvent, FileEventKind, GitInfo, ParsedDocument},
    handoff::Handoff,
    harness::{HarnessProbeState, HarnessStatus, HarnessUpdateRequest, HarnessUpdateResult},
    mcp::{McpProposal, McpRecord},
    pulse::{ActionItem, MetricCard, PulseData, RecentActivity},
    review::{Review, ReviewFinding},
    roadmap::{
        MilestoneAdrSummary, MilestoneDetail, MilestoneOverview, MilestoneReviewSummary,
        MilestoneSpecSummary,
    },
    session::{
        AgentHost, ModelRoute, OllamaModel, SessionExitPayload, SessionInfo,
        SessionOutputPayload, SessionStartRequest, SessionStatus,
    },
    skill::Skill,
    spec::{Spec, SpecParkingEvent},
    statistics::{
        ArtifactFamilyStats, DiagnosticStats, ProjectStatistics, ReviewCycleRankingEntry,
        ReviewDimensionStat, ReviewQualityStats, ReviewTrendPoint, SpecFlowStats, StatusCount,
    },
    wiki::{WikiNode, WikiNodeKind, WikiPage, WikiTree},
    workspace::{
        KitHealth, KitMigrationStatus, WorkspaceInfo, WorkspaceRegistry, WorkspaceSnapshot,
        WorkspaceSummary,
    },
};

fn generate_typescript() -> String {
    let mut out = String::new();
    out.push_str("// ─── Generated by ts-rs from Rust domain and Tauri models ───\n");
    out.push_str("// DO NOT EDIT DIRECTLY. Run `cargo test --test export_types` to regenerate.\n\n");

    let decls = [
        // Status enums
        SpecStatus::decl(),
        ReviewStatus::decl(),
        AdrStatus::decl(),
        AgentStatus::decl(),
        AgentProposalStatus::decl(),
        McpStatus::decl(),
        McpProposalStatus::decl(),
        HandoffStatus::decl(),
        SkillStatus::decl(),
        DebtStatus::decl(),
        // Core Diagnostics
        DiagnosticSeverity::decl(),
        DiagnosticFixability::decl(),
        Diagnostic::decl(),
        // Core Kit Feedback
        KitFeedbackNote::decl(),
        KitFeedbackResolution::decl(),
        KitFeedbackNoteStatus::decl(),
        KitFeedbackReport::decl(),
        // Core Debt & Dream
        Debt::decl(),
        RelationSummary::decl(),
        DebtContext::decl(),
        DebtCandidate::decl(),
        DebtCandidateInventory::decl(),
        Dream::decl(),
        // Core Review Lifecycle
        ReviewEventInput::decl(),
        ReviewLifecycleEvent::decl(),
        ReviewEventHistory::decl(),
        ReviewHistorySource::decl(),
        ReviewLifecycleAnalysis::decl(),
        // Core Branching & Verification
        BranchingTopology::decl(),
        BranchNamingConfig::decl(),
        BranchAuthorityConfig::decl(),
        CommitTriggersConfig::decl(),
        BranchingStrategy::decl(),
        VerificationGate::decl(),
        VerificationManifest::decl(),
        VerificationAttestation::decl(),
        OperatorGate::decl(),
        // Roadmap
        RoadmapMilestone::decl(),
        Roadmap::decl(),
        MilestoneSpecSummary::decl(),
        MilestoneReviewSummary::decl(),
        MilestoneAdrSummary::decl(),
        MilestoneDetail::decl(),
        MilestoneOverview::decl(),
        // Tauri Models
        SpecParkingEvent::decl(),
        Spec::decl(),
        ReviewFinding::decl(),
        Review::decl(),
        Adr::decl(),
        AgentProfile::decl(),
        AgentProposal::decl(),
        Skill::decl(),
        Handoff::decl(),
        McpRecord::decl(),
        McpProposal::decl(),
        DesignMockupKind::decl(),
        DesignMockup::decl(),
        DesignMockupHtml::decl(),
        FileContent::decl(),
        DirEntry::decl(),
        FileEventKind::decl(),
        FileEvent::decl(),
        GitInfo::decl(),
        ParsedDocument::decl(),
        MetricCard::decl(),
        ActionItem::decl(),
        RecentActivity::decl(),
        PulseData::decl(),
        AgentHost::decl(),
        ModelRoute::decl(),
        SessionStatus::decl(),
        SessionStartRequest::decl(),
        SessionInfo::decl(),
        SessionOutputPayload::decl(),
        SessionExitPayload::decl(),
        OllamaModel::decl(),
        StatusCount::decl(),
        ArtifactFamilyStats::decl(),
        SpecFlowStats::decl(),
        ReviewDimensionStat::decl(),
        ReviewTrendPoint::decl(),
        ReviewCycleRankingEntry::decl(),
        ReviewQualityStats::decl(),
        DiagnosticStats::decl(),
        ProjectStatistics::decl(),
        WikiNodeKind::decl(),
        WikiNode::decl(),
        WikiPage::decl(),
        WikiTree::decl(),
        KitHealth::decl(),
        KitMigrationStatus::decl(),
        WorkspaceSummary::decl(),
        WorkspaceInfo::decl(),
        WorkspaceRegistry::decl(),
        WorkspaceSnapshot::decl(),
        HarnessProbeState::decl(),
        HarnessStatus::decl(),
        HarnessUpdateRequest::decl(),
        HarnessUpdateResult::decl(),
    ];

    for decl in decls {
        if !decl.starts_with("export ") {
            out.push_str("export ");
        }
        out.push_str(&decl);
        out.push_str("\n\n");
    }

    out
}

#[test]
fn export_typescript_types() {
    let ts_content = generate_typescript();
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf();
    let target = root.join("src/types/generated.ts");
    std::fs::write(&target, &ts_content).expect("Failed to write generated.ts");
}

#[test]
fn generated_types_are_in_sync() {
    let ts_content = generate_typescript();
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf();
    let target = root.join("src/types/generated.ts");
    let existing = std::fs::read_to_string(&target).unwrap_or_default();
    assert_eq!(
        existing.replace("\r\n", "\n"),
        ts_content.replace("\r\n", "\n"),
        "Generated TypeScript bindings (src/types/generated.ts) are out of date. Run `cargo test --test export_types` to regenerate."
    );
}
