import { describe, it, expect } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";

describe("Type definitions drift check", () => {
  it("generated.ts exists and contains Rust-generated domain types", () => {
    const generatedPath = path.resolve(__dirname, "../types/generated.ts");
    expect(fs.existsSync(generatedPath)).toBe(true);

    const content = fs.readFileSync(generatedPath, "utf-8");
    expect(content).toContain("// ─── Generated by ts-rs from Rust domain and Tauri models ───");

    // Check all 10 domain statuses
    expect(content).toContain('type SpecStatus = "backlog" | "ready" | "working" | "review" | "done" | "discarded"');
    expect(content).toContain('type ReviewStatus = "pending" | "accepted" | "changes-requested" | "blocked" | "superseded"');
    expect(content).toContain('type AdrStatus = "proposed" | "accepted" | "rejected" | "superseded" | "deprecated"');
    expect(content).toContain('type AgentStatus = "proposed" | "active" | "inactive" | "retired"');
    expect(content).toContain('type AgentProposalStatus = "proposed" | "approved" | "rejected"');
    expect(content).toContain('type McpStatus = "specified" | "active" | "inactive" | "deprecated"');
    expect(content).toContain('type McpProposalStatus = "proposed" | "approved" | "rejected" | "implemented" | "blocked"');
    expect(content).toContain('type HandoffStatus = "ready" | "consumed" | "superseded" | "archived"');
    expect(content).toContain('type SkillStatus = "proposed" | "active" | "retired"');
    expect(content).toContain('type DebtStatus = "open" | "planned" | "deferred" | "resolved" | "accepted-risk" | "superseded"');

    // Check core and Tauri model types
    expect(content).toContain("type Spec =");
    expect(content).toContain("type Review =");
    expect(content).toContain("type Debt =");
    expect(content).toContain("type Dream =");
    expect(content).toContain("type Adr =");
    expect(content).toContain("type AgentProfile =");
    expect(content).toContain("type AgentProposal =");
    expect(content).toContain("type Skill =");
    expect(content).toContain("type Handoff =");
    expect(content).toContain("type McpRecord =");
    expect(content).toContain("type McpProposal =");
    expect(content).toContain("type WorkspaceInfo =");
    expect(content).toContain("type WorkspaceSnapshot =");
    expect(content).toContain("type ProjectStatistics =");
  });

  it("index.ts re-exports all generated types", () => {
    const indexPath = path.resolve(__dirname, "../types/index.ts");
    const content = fs.readFileSync(indexPath, "utf-8");
    expect(content).toContain('export * from "./generated"');
  });
});
