// ─── Generated by ts-rs from Rust domain and Tauri models ───
// DO NOT EDIT DIRECTLY. Run `cargo test --test export_types` to regenerate.

export type SpecStatus = "backlog" | "ready" | "working" | "review" | "done" | "discarded";

export type ReviewStatus = "pending" | "accepted" | "changes-requested" | "blocked" | "superseded";

export type AdrStatus = "proposed" | "accepted" | "rejected" | "superseded" | "deprecated";

export type AgentStatus = "proposed" | "active" | "inactive" | "retired";

export type AgentProposalStatus = "proposed" | "approved" | "rejected";

export type McpStatus = "specified" | "active" | "inactive" | "deprecated";

export type McpProposalStatus = "proposed" | "approved" | "rejected" | "implemented" | "blocked";

export type HandoffStatus = "ready" | "consumed" | "superseded" | "archived";

export type SkillStatus = "proposed" | "active" | "retired";

export type DebtStatus = "open" | "planned" | "deferred" | "resolved" | "accepted-risk" | "superseded";

export type DiagnosticSeverity = "info" | "warning" | "error";

export type DiagnosticFixability = "manual" | "governed-mutation" | "read-only";

export type Diagnostic = { schema_version: string, id: string, code: string, severity: DiagnosticSeverity, artifact_id: string | null, path: string | null, message: string, next_action: string, fixability: DiagnosticFixability, };

export type KitFeedbackNote = { id: string, timestamp: string, lmbrain_version: string, category: string, severity: string, summary: string, observed_behavior: string, expected_behavior: string, impact: string, evidence: string, workaround: string | null, suggested_improvement: string | null, related_note: string | null, actor: string, };

export type KitFeedbackResolution = { note_id: string, kind: string, version: string, reference: string | null, timestamp: string, actor: string, };

export type KitFeedbackNoteStatus = { note_id: string, status: string, resolved_in: string | null, reconfirmed_in: Array<string>, };

export type KitFeedbackReport = { schema_version: string, path: string, updated: string, total: number, open: number, resolved: number, counts_by_category: { [key in string]?: number }, counts_by_severity: { [key in string]?: number }, notes: Array<KitFeedbackNote>, resolutions: Array<KitFeedbackResolution>, note_statuses: Array<KitFeedbackNoteStatus>, };

export type KitMigrationItem = { path: string, action: string, classification: string, description: string, };

export type KitMigrationPreview = { from_version: string, to_version: string, digest: string, items: Array<KitMigrationItem>, 
/**
 * Kit-owned paths whose current content differs from the content the
 * installed kit shipped. Realigning them discards a local edit.
 */
locally_modified: Array<string>, can_migrate: boolean, blocker_reason: string | null, };

export type KitMigrationResult = { previous_version: string, current_version: string, updated_items: Array<string>, backed_up_to: string, };

export type Debt = { id: string, title: string, status: string, category: string, severity: string, origin_severity: string | null, area: string | null, milestone: string | null, owner: string | null, origin_artifact: string | null, origin_ref: string | null, related_specs: Array<string>, related_reviews: Array<string>, related_decisions: Array<string>, target_specs: Array<string>, blocked_by: Array<string>, resolution_refs: Array<string>, superseded_by: string | null, created: string, updated: string, tags: Array<string>, body: string, path: string, malformed: boolean, };

export type RelationSummary = { id: string, title: string, status: string, path: string, };

export type DebtContext = { schema_version: string, debt: Debt, origin: RelationSummary | null, related_specs: Array<RelationSummary>, related_reviews: Array<RelationSummary>, related_decisions: Array<RelationSummary>, target_specs: Array<RelationSummary>, blockers: Array<RelationSummary>, resolution_refs: Array<RelationSummary>, superseded_by: RelationSummary | null, events: Array<Record<string, unknown>>, warnings: Array<string>, omitted_relations: number, };

export type DebtCandidate = { origin_artifact: string, origin_ref: string, summary: string, promoted_debt: string | null, inference: string, };

export type DebtCandidateInventory = { schema_version: string, candidates: Array<DebtCandidate>, total: number, omitted: number, mutated: boolean, warnings: Array<string>, };

export type Dream = { id: string, title: string, status: string, classification: string, confidence: string, area: string | null, related_artifacts: Array<string>, context_digest: string, created: string, updated: string, body: string, path: string, malformed: boolean, };

export type ReviewEventInput = { actor_role: string, reason: string, evidence_refs: Array<string>, remediation_agent: string | null, };

export type ReviewLifecycleEvent = { schema_version: string, id: string, timestamp: string, action: string, from_status: string, to_status: string, actor_role: string, reason: string, evidence_refs: Array<string>, implementation_agent: string | null, remediation_agent: string | null, };

export type ReviewEventHistory = { events: Array<ReviewLifecycleEvent>, warnings: Array<string>, };

export type ReviewHistorySource = "structured-events" | "legacy-explicit" | "status-only";

export type ReviewLifecycleAnalysis = { source: ReviewHistorySource, confidence: string, review_passes: number, remediation_cycles: number, initial_verdict: string | null, final_verdict: string | null, escalation_count: number, takeover_count: number, remediation_agents: Array<string>, escalation_owners: Array<string>, takeover_owners: Array<string>, warnings: Array<string>, };

export type BranchingTopology = "main-only" | "github-flow" | "git-flow" | "custom";

export type BranchNamingConfig = { allowed_prefixes: Array<string>, spec_branch_pattern: string, require_prefix: boolean, };

export type BranchAuthorityConfig = { lead_only_push_branches: Array<string>, allow_specialist_push: boolean, require_pr_for_merge: boolean, };

export type CommitTriggersConfig = { commit_on_spec_completion: boolean, commit_on_doc_change: boolean, };

export type BranchingStrategy = { schema_version: number, topology: BranchingTopology, default_branch: string, protected_branches: Array<string>, development_branch: string | null, branch_naming: BranchNamingConfig, authority: BranchAuthorityConfig, commit_triggers: CommitTriggersConfig, };

export type VerificationGate = { id: string, title: string | null, program: string, args: Array<string>, cwd: string, timeout_seconds: bigint | null, output_limit_bytes: number | null, expected_exit_code: number | null, result_matcher: string | null, environment: { [key in string]?: string }, fingerprint_exclude: Array<string>, };

export type VerificationManifest = { schema_version: number, gates: Array<VerificationGate>, };

export type VerificationAttestation = { schema_version: string, id: string, requirement_id: string, requirement_digest: string, actor_role: string, actor: string, timestamp: string, result: string, evidence_ref: string, evidence_digest: string | null, 
/**
 * Present only on operator attestations recorded by the Lead on the
 * operator's explicit out-of-band authorization (#94 / KIT-NOTE-011).
 * Absence means the authority attested directly (desktop panel or
 * spec_attest_lead).
 */
delegated_by: string | null, delegation_channel: string | null, delegation_authorization: string | null, };

export type OperatorGate = { spec_id: string, spec_title: string, spec_status: string, spec_path: string, requirement_id: string, text: string, kind: string, evidence_kind: string, checked: boolean, attested: VerificationAttestation | null, blocker: string | null, milestone: string | null, updated: string, };

export type RoadmapMilestone = { id: string, title: string, status: string, outcome: string, specs: Array<string>, decisions: Array<string>, risks: Array<string>, depends_on: string | null, };

export type Roadmap = { title: string, milestones: Array<RoadmapMilestone>, };

export type MilestoneSpecSummary = { id: string, title: string, status: string, priority: string | null, area: string | null, recommended_agent: string | null, path: string | null, };

export type MilestoneReviewSummary = { id: string, title: string, status: string, spec_id: string | null, path: string | null, };

export type MilestoneAdrSummary = { id: string, title: string, status: string, path: string | null, };

export type MilestoneDetail = { id: string, title: string, status: string, outcome: string, depends_on: string | null, risks: Array<string>, spec_count: number, spec_counts_by_status: { [key in string]?: number }, specs: Array<MilestoneSpecSummary>, reviews: Array<MilestoneReviewSummary>, decisions: Array<MilestoneAdrSummary>, unresolved_refs: Array<string>, next_action: string | null, progress_pct: number, };

export type MilestoneOverview = { title: string, milestones: Array<MilestoneDetail>, unmapped_specs: Array<MilestoneSpecSummary>, warnings: Array<string>, };

export type SpecParkingEvent = { timestamp: string, actor: string, reason: string, revisit_condition: string | null, };

export type Spec = { id: string, title: string, status: SpecStatus, priority: string | null, area: string | null, milestone: string | null, recommended_agent: string | null, 
/**
 * Lead-owned implementation estimate (issue #64). Optional in the parser:
 * it is mandatory only at the `ready` transition, so legacy specs load.
 */
capability_tier: string | null, thinking_level: string | null, depends_on: Array<string>, parking_events: Array<SpecParkingEvent>, skills: Array<string>, body: string, path: string, created: string, updated: string, tags: Array<string>, links: Array<string>, related_tasks: Array<string>, related_decisions: Array<string>, malformed: boolean | null, };

export type ReviewFinding = { id: string, text: string, severity: string, };

export type Review = { id: string, title: string, status: ReviewStatus, spec_id: string | null, reviewer: string | null, implementation_agent: string | null, finding_categories: Array<string>, findings: Array<ReviewFinding>, events: Array<ReviewLifecycleEvent>, lifecycle: ReviewLifecycleAnalysis, lifecycle_warnings: Array<string>, body: string, path: string, created: string, updated: string, tags: Array<string>, links: Array<string>, malformed: boolean | null, };

export type Adr = { id: string, title: string, status: AdrStatus, decision_date: string | null, decider: string | null, body: string, path: string, created: string, updated: string, tags: Array<string>, links: Array<string>, 
/**
 * Decisions this one retires, and the one that retired it (issue #48).
 * Both are optional in the artifact: records predating the governed
 * supersession parse to empty rather than failing.
 */
supersedes: Array<string>, superseded_by: Array<string>, malformed: boolean | null, };

export type AgentProfile = { id: string, title: string, mnemonic_name: string | null, status: AgentStatus, role: string | null, activation: string | null, can_implement: boolean | null, can_review: boolean | null, domains: Array<string> | null, primary_files: Array<string> | null, review_focus: Array<string> | null, context_pack: string | null, constraints: Array<string> | null, skills: Array<string> | null, body: string, path: string, created: string, updated: string, tags: Array<string>, links: Array<string>, malformed: boolean | null, };

export type AgentProposal = { id: string, title: string, status: AgentProposalStatus, proposed_mnemonic_name: string | null, proposal_type: string | null, target_profile: string | null, body: string, path: string, created: string, updated: string, tags: Array<string>, links: Array<string>, malformed: boolean | null, };

export type Skill = { id: string, title: string, status: SkillStatus, scope: string | null, kind: string | null, risk: string | null, applies_to: Array<string>, domains: Array<string>, commands: Array<string>, requires_operator_approval: boolean | null, body: string, path: string, created: string, updated: string, tags: Array<string>, links: Array<string>, malformed: boolean | null, };

export type Handoff = { id: string, title: string, status: HandoffStatus, body: string, path: string, created: string, updated: string, tags: Array<string>, links: Array<string>, malformed: boolean | null, };

export type McpRecord = { id: string, title: string, status: McpStatus, body: string, path: string, created: string, updated: string, tags: Array<string>, links: Array<string>, malformed: boolean | null, };

export type McpProposal = { id: string, title: string, status: McpProposalStatus, body: string, path: string, created: string, updated: string, tags: Array<string>, links: Array<string>, malformed: boolean | null, };

export type DesignMockupKind = "package" | "html-file";

export type DesignMockup = { id: string, name: string, path: string, entry_path: string, kind: DesignMockupKind, modified: string | null, size: bigint, summary: string | null, manifest_title: string | null, manifest_description: string | null, has_manifest: boolean, has_readme: boolean, };

export type DesignMockupHtml = { path: string, content: string, };

export type FileContent = { path: string, content: string, size: bigint, modified: string, };

export type DirEntry = { name: string, path: string, is_dir: boolean, size: bigint | null, modified: string | null, };

export type FileEventKind = "created" | "modified" | "removed";

export type FileEvent = { kind: FileEventKind, path: string, };

export type GitInfo = { branch: string | null, is_clean: boolean | null, current_commit: string | null, };

export type ParsedDocument = { path: string, frontmatter: Record<string, unknown>, body: string, wikilinks: Array<string>, diagnostics: Array<string>, malformed: boolean, };

export type MetricCard = { label: string, count: number, accent: string, };

export type ActionItem = { title: string, description: string, action_type: string, spec_id: string | null, agent: string | null, };

export type RecentActivity = { action: string, path: string, description: string, timestamp: string, };

export type PulseData = { focus: string | null, milestone: string | null, milestone_progress: number | null, milestone_due: string | null, metrics: Array<MetricCard>, actions: Array<ActionItem>, blockers: Array<ActionItem>, recent_activity: Array<RecentActivity>, ready_handoffs: Array<Handoff>, active_handoff: Handoff | null, };

export type AgentHost = "claude" | "codex" | "pi" | "opencode";

export type ModelRoute = "native" | "ollama";

export type SessionStatus = "running" | "exited";

export type SessionStartRequest = { host: AgentHost, route: ModelRoute, model: string | null, label: string | null, codex_bin: string | null, };

export type SessionInfo = { id: string, label: string, host: AgentHost, route: ModelRoute, model: string | null, status: SessionStatus, exit_code: number | null, };

export type SessionOutputPayload = { id: string, data: string, };

export type SessionExitPayload = { id: string, code: number | null, };

export type OllamaModel = { name: string, cloud: boolean, capabilities: Array<string>, };

export type StatusCount = { status: string, count: number, };

export type ArtifactFamilyStats = { family: string, label: string, total: number, statuses: Array<StatusCount>, };

export type SpecFlowStats = { total_specs: number, done_specs: number, open_specs: number, done_ratio: number, by_status: Array<StatusCount>, by_priority: Array<StatusCount>, by_area: Array<StatusCount>, };

export type ReviewDimensionStat = { value: string, reviewed_specs: number, specs_with_changes_requested: number, change_request_rate: number, };

export type ReviewTrendPoint = { period: string, total_reviews: number, accepted_reviews: number, changes_requested_reviews: number, reviewed_specs: number, specs_with_changes_requested: number, };

export type ReviewCycleRankingEntry = { spec_id: string, title: string, path: string, status: string, review_count: number, review_passes: number, remediation_cycles: number, history_source: string, confidence: string, warnings: Array<string>, };

export type ReviewQualityStats = { total_reviews: number, total_review_passes: number, remediation_cycles: number, escalation_count: number, takeover_count: number, lifecycle_known_reviews: number, lifecycle_coverage: number, reviewed_specs: number, accepted_reviews: number, changes_requested_reviews: number, blocked_reviews: number, superseded_reviews: number, reviews_without_spec: number, reviews_without_created: number, specs_with_changes_requested: number, specs_with_multiple_changes_requested: number, change_request_rate: number, first_pass_eligible_specs: number, first_pass_accepted_specs: number, first_pass_acceptance_rate: number, average_reviews_per_reviewed_spec: number, review_cycle_ranking: Array<ReviewCycleRankingEntry>, review_cycle_ranking_coverage: number, by_area: Array<ReviewDimensionStat>, by_agent: Array<ReviewDimensionStat>, trend: Array<ReviewTrendPoint>, };

export type DiagnosticStats = { total: number, warnings: number, errors: number, by_family: Array<StatusCount>, };

export type ProjectStatistics = { artifact_families: Array<ArtifactFamilyStats>, spec_flow: SpecFlowStats, review_quality: ReviewQualityStats, diagnostics: DiagnosticStats, };

export type WikiNodeKind = "file" | "folder" | "knowledge" | "decisions" | "specs" | "tasks" | "reviews" | "debts" | "handoffs" | "agents" | "mcp";

export type WikiNode = { name: string, path: string, kind: WikiNodeKind, children: Array<WikiNode>, count: number | null, };

export type WikiPage = { path: string, name: string, content_html: string, frontmatter: { [key in string]?: string }, wikilinks: Array<string>, backlinks: Array<string>, updated: string | null, word_count: number | null, };

export type WikiTree = { root: WikiNode, };

export type KitHealth = "ok" | "warn" | "none";

export type KitMigrationStatus = "up-to-date" | "migration-available" | "project-newer-than-app" | "unknown-project-version" | "unknown-bundled-version" | "migration-guidance-missing";

export type WorkspaceSummary = { path: string, name: string, health: KitHealth, last_opened: string, branch: string | null, is_clean: boolean | null, };

export type WorkspaceInfo = { path: string, name: string, kit_version: string, health: KitHealth, diagnostics: Array<Diagnostic>, branch: string | null, is_clean: boolean | null, spec_count: number, debt_count: number, task_count: number, decision_count: number, agent_count: number, project_kit_version: string, bundled_kit_version: string, bundled_kit_path: string, kit_migration_status: KitMigrationStatus, };

export type WorkspaceRegistry = { recent: Array<WorkspaceSummary>, pinned: Array<string>, };

export type WorkspaceSnapshot = { pulse_data: PulseData, specs: Array<Spec>, reviews: Array<Review>, debts: Array<Debt>, dreams: Array<Dream>, adrs: Array<Adr>, agents: Array<AgentProfile>, agent_proposals: Array<AgentProposal>, mcp_records: Array<McpRecord>, mcp_proposals: Array<McpProposal>, skills: Array<Skill>, handoffs: Array<Handoff>, diagnostics: Array<Diagnostic>, project_statistics: ProjectStatistics, operator_gates: Array<OperatorGate>, };

export type HarnessProbeState = "installed" | "missing" | "error";

export type HarnessStatus = { host: AgentHost, label: string, state: HarnessProbeState, executable: string | null, version: string | null, detail: string | null, probed_at: string, install_url: string, install_command: string, };

export type HarnessUpdateRequest = { host: AgentHost, codex_bin: string | null, };

export type HarnessUpdateResult = { host: AgentHost, success: boolean, already_current: boolean, before: HarnessStatus, after: HarnessStatus, exit_code: number | null, timed_out: boolean, stdout: string, stderr: string, };

