//! Experimental, opt-in decision maps. These artifacts deliberately sit beside
//! the delivery board: they shape a route to a spec and never authorize work.

use std::{collections::{BTreeMap, BTreeSet}, fs, path::{Path, PathBuf}};

use chrono::Local;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::{frontmatter::{atomic_write, Document, FrontmatterError}, mutation_lock::WorkspaceLock, path::PathGuard, transitions::MutationResult};

pub const WAYFINDER_EVENT_SCHEMA_VERSION: &str = "1";
const MAP_STATUSES: &[&str] = &["draft", "active", "cleared", "superseded", "abandoned", "archived"];
const TICKET_STATUSES: &[&str] = &["open", "claimed", "resolved", "out_of_scope", "superseded"];
const TICKET_TYPES: &[&str] = &["conversation", "prototype", "research", "prerequisite"];

#[derive(Debug, Clone, Serialize, Deserialize, ts_rs::TS)]
pub struct WayfinderFog { pub id: String, pub summary: String, pub provenance: String, pub state: String, pub graduated_to: Option<String> }
#[derive(Debug, Clone, Serialize, Deserialize, ts_rs::TS)]
pub struct WayfinderMap { pub id: String, pub title: String, pub status: String, pub destination: String, pub fog: Vec<WayfinderFog>, pub path: String, pub updated: String, pub malformed: bool }
#[derive(Debug, Clone, Serialize, Deserialize, ts_rs::TS)]
pub struct WayfinderTicket { pub id: String, pub map: String, pub title: String, pub status: String, pub ticket_type: String, pub question: String, pub blockers: Vec<String>, pub claimed_by: Option<String>, pub claimed_at: Option<String>, pub resolution_summary: Option<String>, pub path: String, pub malformed: bool }
#[derive(Debug, Clone, Serialize, Deserialize, ts_rs::TS)]
pub struct WayfinderOverview { pub maps: Vec<WayfinderMapSummary> }
#[derive(Debug, Clone, Serialize, Deserialize, ts_rs::TS)]
pub struct WayfinderMapSummary { pub id: String, pub title: String, pub status: String, pub destination: String, pub frontier_count: usize, pub claimed_count: usize, pub blocked_count: usize, pub fog_count: usize, pub resolved_count: usize, pub updated: String }
#[derive(Debug, Clone, Serialize, Deserialize, ts_rs::TS)]
pub struct WayfinderMapContext { pub map: WayfinderMap, pub frontier: Vec<WayfinderTicket>, pub blocked: Vec<WayfinderTicket>, pub claimed: Vec<WayfinderTicket>, pub resolved: Vec<WayfinderTicket>, pub diagnostics: Vec<String>, pub omitted_ticket_count: usize }
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WayfinderMapCreate { pub title: String, pub destination: String, pub notes: String, pub out_of_scope: String, pub actor: String }
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WayfinderTicketCreate { pub map: String, pub title: String, pub ticket_type: String, pub question: String, #[serde(default)] pub blockers: Vec<String>, pub bounded_context: String, pub actor: String }

#[derive(Debug, Error)]
pub enum WayfinderError { #[error(transparent)] Path(#[from] crate::path::PathError), #[error(transparent)] Io(#[from] std::io::Error), #[error(transparent)] Frontmatter(#[from] FrontmatterError), #[error("invalid Wayfinder artifact: {0}")] Invalid(String), #[error("artifact not found: {0}")] NotFound(String) }

pub fn overview(root: impl AsRef<Path>) -> WayfinderOverview {
    let root = root.as_ref(); let maps = list_maps(root); let tickets = list_tickets(root);
    WayfinderOverview { maps: maps.into_iter().map(|map| { let (frontier, blocked, claimed) = classified(&tickets, &map.id); let resolved_count = tickets.iter().filter(|ticket| ticket.map == map.id && ticket.status == "resolved").count(); WayfinderMapSummary { id: map.id, title: map.title, status: map.status, destination: map.destination, fog_count: map.fog.iter().filter(|fog| fog.state == "active").count(), resolved_count, frontier_count: frontier.len(), blocked_count: blocked.len(), claimed_count: claimed.len(), updated: map.updated } }).collect() }
}

pub fn map_context(root: impl AsRef<Path>, map_id: &str) -> Result<WayfinderMapContext, WayfinderError> {
    let root = root.as_ref(); let map = list_maps(root).into_iter().find(|map| map.id == map_id).ok_or_else(|| WayfinderError::NotFound(map_id.into()))?; let tickets = list_tickets(root); let (frontier, blocked, claimed) = classified(&tickets, map_id); let resolved = tickets.iter().filter(|ticket| ticket.map == map_id && matches!(ticket.status.as_str(), "resolved" | "out_of_scope" | "superseded")).cloned().collect(); let diagnostics = validate_map(&map, &tickets); Ok(WayfinderMapContext { map, frontier, blocked, claimed, resolved, diagnostics, omitted_ticket_count: 0 })
}

pub fn list_maps(root: impl AsRef<Path>) -> Vec<WayfinderMap> { scan(root.as_ref().join(".lmbrain/wayfinder/maps"), parse_map) }
pub fn list_tickets(root: impl AsRef<Path>) -> Vec<WayfinderTicket> { scan(root.as_ref().join(".lmbrain/wayfinder/tickets"), parse_ticket) }

pub fn create_map(root: impl AsRef<Path>, input: WayfinderMapCreate) -> Result<MutationResult, WayfinderError> {
    required(&[("title", &input.title), ("destination", &input.destination), ("actor", &input.actor)])?; let guard = PathGuard::new(root)?; let _lock = WorkspaceLock::acquire(guard.root())?; let id = next_id(guard.root(), "MAP"); let date = today(); let path = guard.root().join(".lmbrain/wayfinder/maps").join(format!("{id}.md")); let content = format!("---\nid: {id}\ntitle: {}\nstatus: draft\ndestination: {}\nnotes: {}\nout_of_scope: {}\nfog: []\ncreated: {date}\nupdated: {date}\nwayfinder_events: [{}]\n---\n# {}\n", q(&input.title), q(&input.destination), q(&input.notes), q(&input.out_of_scope), event("created", &input.actor), input.title.trim()); atomic_write(&path, &content)?; Ok(result(id, "draft", guard.root(), &path))
}

pub fn create_ticket(root: impl AsRef<Path>, input: WayfinderTicketCreate) -> Result<MutationResult, WayfinderError> {
    required(&[("map", &input.map), ("title", &input.title), ("question", &input.question), ("actor", &input.actor)])?; if !TICKET_TYPES.contains(&input.ticket_type.as_str()) { return Err(WayfinderError::Invalid("ticket_type must be conversation, prototype, research, or prerequisite".into())); } let guard = PathGuard::new(root)?; let _lock = WorkspaceLock::acquire(guard.root())?; let maps = list_maps(guard.root()); if !maps.iter().any(|map| map.id == input.map) { return Err(WayfinderError::NotFound(input.map)); } let tickets = list_tickets(guard.root()); validate_blockers(&input.map, &input.blockers, &tickets)?; let id = next_id(guard.root(), "WAY"); let date = today(); let path = guard.root().join(".lmbrain/wayfinder/tickets").join(format!("{id}.md")); let content = format!("---\nid: {id}\ntitle: {}\nstatus: open\nmap: {}\nticket_type: {}\nquestion: {}\nblockers: {}\nclaimed_by: null\nclaimed_at: null\nresolution_summary: null\ncreated: {date}\nupdated: {date}\nwayfinder_events: [{}]\n---\n# {}\n\n## Bounded context\n\n{}\n", q(&input.title), q(&input.map), q(&input.ticket_type), q(&input.question), array(&input.blockers), event("created", &input.actor), input.title.trim(), input.bounded_context.trim()); atomic_write(&path, &content)?; Ok(result(id, "open", guard.root(), &path))
}

pub fn claim_ticket(root: impl AsRef<Path>, ticket_id: &str, claimant: &str) -> Result<MutationResult, WayfinderError> { mutate_ticket(root, ticket_id, claimant, |doc| { if doc.value("status").as_deref() != Some("open") { return Err(WayfinderError::Invalid("only an open frontier ticket can be claimed".into())); } doc.set("status", "claimed"); doc.set("claimed_by", &q(claimant)); doc.set("claimed_at", &q(&Local::now().to_rfc3339())); Ok("claimed") }) }
pub fn release_ticket(root: impl AsRef<Path>, ticket_id: &str, actor: &str) -> Result<MutationResult, WayfinderError> { mutate_ticket(root, ticket_id, actor, |doc| { if doc.value("status").as_deref() != Some("claimed") { return Err(WayfinderError::Invalid("only a claimed ticket can be released".into())); } doc.set("status", "open"); doc.set("claimed_by", "null"); doc.set("claimed_at", "null"); Ok("open") }) }
pub fn resolve_ticket(root: impl AsRef<Path>, ticket_id: &str, actor: &str, summary: &str, evidence: &str, operator_evidence: Option<&str>) -> Result<MutationResult, WayfinderError> { required(&[("actor", actor), ("summary", summary), ("evidence", evidence)])?; mutate_ticket(root, ticket_id, actor, |doc| { let ticket_type = doc.value("ticket_type").unwrap_or_default(); if matches!(ticket_type.as_str(), "conversation" | "prototype") && operator_evidence.unwrap_or_default().trim().is_empty() { return Err(WayfinderError::Invalid("conversation and prototype tickets require explicit operator evidence".into())); } if !matches!(doc.value("status").as_deref(), Some("open") | Some("claimed")) { return Err(WayfinderError::Invalid("only an open or claimed ticket can be resolved".into())); } doc.set("status", "resolved"); doc.set("resolution_summary", &q(summary)); doc.set("resolution_evidence", &q(evidence)); doc.set("operator_evidence", &operator_evidence.map(q).unwrap_or_else(|| "null".into())); Ok("resolved") }) }
pub fn clear_map(root: impl AsRef<Path>, map_id: &str, actor: &str) -> Result<MutationResult, WayfinderError> { let guard = PathGuard::new(root)?; let _lock = WorkspaceLock::acquire(guard.root())?; let context = map_context(guard.root(), map_id)?; if !context.diagnostics.is_empty() || !context.map.fog.iter().all(|fog| fog.state != "active") || !context.frontier.is_empty() || !context.blocked.is_empty() || !context.claimed.is_empty() { return Err(WayfinderError::Invalid("map cannot clear while diagnostics, active fog, or unresolved tickets remain".into())); } let path = guard.root().join(".lmbrain/wayfinder/maps").join(format!("{map_id}.md")); let mut doc = Document::parse(&fs::read_to_string(&path)?)?; doc.set("status", "cleared"); doc.set("updated", &today()); doc.set("wayfinder_events", &format!("[{}]", event("cleared", actor))); atomic_write(&path, &doc.render())?; Ok(result(map_id.into(), "cleared", guard.root(), &path)) }

fn mutate_ticket(root: impl AsRef<Path>, ticket_id: &str, actor: &str, change: impl FnOnce(&mut Document) -> Result<&'static str, WayfinderError>) -> Result<MutationResult, WayfinderError> { let guard = PathGuard::new(root)?; let _lock = WorkspaceLock::acquire(guard.root())?; let path = guard.root().join(".lmbrain/wayfinder/tickets").join(format!("{ticket_id}.md")); if !path.exists() { return Err(WayfinderError::NotFound(ticket_id.into())); } let source = fs::read_to_string(&path)?; let mut doc = Document::parse(&source)?; let status = change(&mut doc)?; doc.set("updated", &today()); doc.set("wayfinder_events", &format!("[{}]", event(status, actor))); atomic_write(&path, &doc.render())?; Ok(result(ticket_id.into(), status, guard.root(), &path)) }

fn classified(tickets: &[WayfinderTicket], map: &str) -> (Vec<WayfinderTicket>, Vec<WayfinderTicket>, Vec<WayfinderTicket>) { let resolved: BTreeSet<&str> = tickets.iter().filter(|ticket| matches!(ticket.status.as_str(), "resolved" | "out_of_scope" | "superseded")).map(|ticket| ticket.id.as_str()).collect(); let mut frontier = vec![]; let mut blocked = vec![]; let mut claimed = vec![]; for ticket in tickets.iter().filter(|ticket| ticket.map == map) { if ticket.status == "claimed" { claimed.push(ticket.clone()); } else if ticket.status == "open" { if ticket.blockers.iter().all(|blocker| resolved.contains(blocker.as_str())) { frontier.push(ticket.clone()); } else { blocked.push(ticket.clone()); } } } (frontier, blocked, claimed) }
fn validate_map(map: &WayfinderMap, tickets: &[WayfinderTicket]) -> Vec<String> { let mut diagnostics = vec![]; if map.destination.trim().is_empty() { diagnostics.push("map destination is required".into()); } if !MAP_STATUSES.contains(&map.status.as_str()) { diagnostics.push(format!("invalid map status: {}", map.status)); } let mut fog = BTreeSet::new(); for item in &map.fog { if !fog.insert(&item.id) { diagnostics.push(format!("duplicate fog id: {}", item.id)); } } for ticket in tickets.iter().filter(|ticket| ticket.map == map.id) { if ticket.question.trim().is_empty() { diagnostics.push(format!("{} has no precise question", ticket.id)); } if !TICKET_TYPES.contains(&ticket.ticket_type.as_str()) || !TICKET_STATUSES.contains(&ticket.status.as_str()) { diagnostics.push(format!("{} has invalid type or status", ticket.id)); } } diagnostics }
fn validate_blockers(map: &str, blockers: &[String], tickets: &[WayfinderTicket]) -> Result<(), WayfinderError> { let ids: BTreeMap<&str, &WayfinderTicket> = tickets.iter().map(|ticket| (ticket.id.as_str(), ticket)).collect(); for blocker in blockers { let ticket = ids.get(blocker.as_str()).ok_or_else(|| WayfinderError::Invalid(format!("blocker {blocker} does not exist")))?; if ticket.map != map { return Err(WayfinderError::Invalid(format!("blocker {blocker} belongs to another map"))); } } Ok(()) }
fn parse_map(path: &Path, doc: &Document) -> WayfinderMap { WayfinderMap { id: doc.value("id").unwrap_or_else(|| "MALFORMED".into()), title: doc.value("title").unwrap_or_else(|| "Malformed map".into()), status: doc.value("status").unwrap_or_default(), destination: doc.value("destination").unwrap_or_default(), fog: doc.object_array("fog").into_iter().map(|item| WayfinderFog { id: item.get("id").and_then(|v| v.as_str()).unwrap_or_default().into(), summary: item.get("summary").and_then(|v| v.as_str()).unwrap_or_default().into(), provenance: item.get("provenance").and_then(|v| v.as_str()).unwrap_or_default().into(), state: item.get("state").and_then(|v| v.as_str()).unwrap_or("active").into(), graduated_to: item.get("graduated_to").and_then(|v| v.as_str()).map(str::to_owned) }).collect(), path: path.to_string_lossy().replace('\\', "/"), updated: doc.value("updated").unwrap_or_default(), malformed: false } }
fn parse_ticket(path: &Path, doc: &Document) -> WayfinderTicket { WayfinderTicket { id: doc.value("id").unwrap_or_else(|| "MALFORMED".into()), map: doc.value("map").unwrap_or_default(), title: doc.value("title").unwrap_or_else(|| "Malformed ticket".into()), status: doc.value("status").unwrap_or_default(), ticket_type: doc.value("ticket_type").unwrap_or_default(), question: doc.value("question").unwrap_or_default(), blockers: doc.string_array("blockers"), claimed_by: doc.value("claimed_by"), claimed_at: doc.value("claimed_at"), resolution_summary: doc.value("resolution_summary"), path: path.to_string_lossy().replace('\\', "/"), malformed: false } }
fn scan<T>(dir: PathBuf, parse: fn(&Path, &Document) -> T) -> Vec<T> { let mut items = vec![]; if let Ok(entries) = fs::read_dir(dir) { for entry in entries.flatten() { let path = entry.path(); if path.extension().and_then(|v| v.to_str()) == Some("md") { if let Ok(source) = fs::read_to_string(&path) { if let Ok(doc) = Document::parse(&source) { items.push(parse(&path, &doc)); } } } } } items }
fn next_id(root: &Path, prefix: &str) -> String { let values: Vec<String> = if prefix == "MAP" { list_maps(root).into_iter().map(|map| map.id).collect() } else { list_tickets(root).into_iter().map(|ticket| ticket.id).collect() }; let max = values.into_iter().filter_map(|id| id.strip_prefix(&format!("{prefix}-"))?.parse::<u32>().ok()).max().unwrap_or(0); format!("{prefix}-{:03}", max + 1) }
fn required(values: &[(&str, &str)]) -> Result<(), WayfinderError> { for (name, value) in values { if value.trim().is_empty() { return Err(WayfinderError::Invalid(format!("{name} is required"))); } } Ok(()) }
fn event(action: &str, actor: &str) -> String { format!("{{schema_version: {}, timestamp: {}, action: {}, actor: {}}}", q(WAYFINDER_EVENT_SCHEMA_VERSION), q(&Local::now().to_rfc3339()), q(action), q(actor)) }
fn q(value: &str) -> String { serde_json::to_string(value.trim()).unwrap() }
fn array(values: &[String]) -> String { format!("[{}]", values.iter().map(|value| q(value)).collect::<Vec<_>>().join(", ")) }
fn today() -> String { Local::now().format("%Y-%m-%d").to_string() }
fn result(id: String, status: &str, root: &Path, path: &Path) -> MutationResult { MutationResult { id, status: status.into(), path: path.strip_prefix(root).unwrap_or(path).to_path_buf(), forced: false } }
